name: milesflutterv2
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  frame_sdk: ^0.0.7
  provider: ^6.0.0  # Use the latest version
  sqflite: ^2.3.0
  path: ^1.8.3
  http: ^1.2.2
  http_parser: ^4.0.0
  flutter_background: ^1.3.0+1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  path_provider: ^2.0.15  # Use the latest version
  google_fonts: ^5.1.0
  model_viewer_plus: ^1.7.0
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.3.6  # Use the latest version
  rxdart: ^0.27.7
  cheetah_flutter: ^2.0.1
  anthropic_sdk_dart: ^0.1.0
  collection: ^1.15.0
  intl: ^0.19.0  # Use the latest version availablez
  deepgram_speech_to_text: ^2.3.2
  record: ^5.1.2
  permission_handler: ^10.0.0  # Use the latest version
  web_socket_channel: ^2.1.0
  audioplayers: ^6.1.0
  supabase_flutter: ^2.0.0
  dart_eval: ^0.7.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/models/
    - assets/
    - assets/images/
    - assets/images/2x/
    - assets/cheetah_params.pv

  fonts:
    - family: Pixelify Sans
      fonts:
        - asset: assets/Pixelify_Sans/PixelifySans-VariableFont_wght.ttf